widgets:
  main_content:
    stories:
      partial: '/shared/stories'
    stories_short:
      partial: '/shared/stories_short'
    featured_content:
      partial: '/shared/featured_items'
      locals: 'featured_items'
      load_functions: 'load_featured_items'
    auto_feature:
      partial: '/shared/auto_feature'      
    ads_banner:
      partial: '/shared/ads_banner'
    newest_images:
      partial: '/shared/sidebar/newest_images'
    announcements:
      partial: 'shared/announcements'    
  sidebar_content:
    gallery_images:
      partial: '/shared/sidebar/gallery_images'
    auto_feature_sidebar:
      partial: '/shared/sidebar/auto_feature_sidebar'      
    newest_stories:
      partial: '/shared/sidebar/newest_stories'
    top_stories:
      partial: '/shared/sidebar/top_stories'
      locals: 'top_stories'
    top_discussed_stories:
      partial: '/shared/sidebar/top_discussed_stories'
      locals: 'most_discussed_stories'
    top_articles:
      partial: '/shared/sidebar/top_articles'
    newest_articles:
      partial: '/shared/sidebar/newest_articles'
      load_functions: 'load_newest_articles'
      locals: 'newest_articles'
    ad_skyscraper:
      locals: 'slot_widget_skyscraper'
      load_functions: 'load_ad_skyscraper'
      partial: '/shared/ads_banner'
    ad_small_square:
      locals: 'slot_widget_small_square'
      load_functions: 'load_ad_small_square'
      partial: '/shared/ads_banner'
    ad_square:
      locals: 'slot_widget_square'
      load_functions: 'load_ad_square'
      partial: '/shared/ads_banner'        
    ad_medium_rectangle:
      locals: 'slot_widget_medium_rectangle'
      load_functions: 'load_ad_medium_rectangle'
      partial: '/shared/ads_banner'        
    ad_large_rectangle:        
      locals: 'slot_widget_large_rectangle'
      load_functions: 'load_ad_large_rectangle'
      partial: '/shared/ads_banner'        
    welcome_panel:
      partial: '/shared/sidebar/welcome_panel'
      locals: 'welcome_message'
    top_users:
      partial: '/shared/sidebar/top_users'
      locals: 'top_users'
    top_users_weekly:
      partial: '/shared/sidebar/top_users_weekly'
      locals: 'top_users_weekly'
    newest_users:
      partial: '/shared/sidebar/newest_users'
      locals: 'newest_users'
    fan_application:
      partial: '/shared/sidebar/fan_application'
    add_bookmark:
      partial: '/shared/sidebar/add_bookmark'
    active_users:
      partial: '/shared/sidebar/active_users'
    recent_users:
      partial: '/shared/sidebar/recent_users'
    rotate_featured:
      partial: '/shared/sidebar/rotate_featured'
    rotate_idea_widgets:
      partial: '/shared/sidebar/rotate_idea_widgets'
    rotate_user_widgets:
      partial: '/shared/sidebar/rotate_user_widgets'
    rotate_article_widgets:
      partial: '/shared/sidebar/rotate_article_widgets'
    top_ideas:
      partial: '/shared/sidebar/top_ideas'
      locals: 'top_ideas'
    newest_ideas:
      partial: '/shared/sidebar/newest_ideas'
      locals: 'newest_ideas'
    featured_idea:
      partial: '/shared/sidebar/featured_idea'
      locals: 'featured_ideas'
    top_resources:
      partial: '/shared/sidebar/top_resources'
      locals: 'top_resources'
    newest_resources:
      partial: '/shared/sidebar/newest_resources'
      locals: 'newest_resources'
    featured_resource:
      partial: '/shared/sidebar/featured_resource'
      locals: 'featured_resources'
    top_events:
      partial: '/shared/sidebar/top_events'
      locals: 'top_events'
    newest_events:
      partial: '/shared/sidebar/newest_events'
      locals: 'newest_events'
    featured_event:
      partial: '/shared/sidebar/featured_event'
      locals: 'featured_events'
    featured_forum:
      partial: '/shared/sidebar/featured_forum'
      locals: 'featured_forum'
    featured_article:
      partial: '/shared/sidebar/featured_article'
      locals: 'featured_articles'
    featured_comment:
      partial: '/shared/sidebar/featured_comment'
      locals: 'featured_comments'        
    blog_roll:
      partial: '/shared/sidebar/blog_roll'
      locals: 'blog_roll'              
    feed_roll:
      partial: '/shared/sidebar/feed_roll'
      locals: 'feed_roll'      
    forum_roll:
      partial: '/shared/sidebar/forum_roll'
      locals: 'forum_roll'      
    resource_section_roll:
      partial: '/shared/sidebar/resource_section_roll'
      locals: 'resource_section_roll'      
    newest_newswires:
      partial: '/shared/sidebar/newest_newswires'
      locals: 'newest_newswires'
    newest_topics:
      partial: '/shared/sidebar/newest_topics'
    rotate_question_widgets:
      partial: '/shared/sidebar/rotate_question_widgets'
    top_answers:
      partial: '/shared/sidebar/top_answers'
    newest_answers:
      partial: '/shared/sidebar/newest_answers'
    top_questions:
      partial: '/shared/sidebar/top_questions'
    newest_questions:
      partial: '/shared/sidebar/newest_questions'
    featured_question:
      partial: '/shared/sidebar/featured_question'
    featured_answer:
      partial: '/shared/sidebar/featured_answer'
    latest_activity:
      partial: '/shared/sidebar/latest_pfeeds'
    google_search:
      partial: '/shared/sidebar/google_search'